### ISSUE TITLE
Log Uploader Error

### ISSUE THREAD

**Issue by kiwikwik** [tvaddonsco/plugin.program.indigo#11]
I am running Kodi 18 beta 4 on Android 7.1.1 with TvAddons/Indigo 4.0.8.

I tried to upload my log today to report a problem I'm having with Kodi but it is erroring out both on the Log Uploader menu item and the Log Uploader button at the bottom of the Log Viewer tool.   In simplified notation, I'm seeing a Python [ERR 7] server not found message in the log file.

I found a way to post the Log for both of my issues.  It was a little too big to upload, so it is in two halves.  The errors related to your app are at the end of the second file.

- 1st half: https://paste.kodi.tv/hahamirayi.kodi
- 2nd half: https://paste.kodi.tv/ubocuhazum.kodi

Perhaps this is related to your recent server problems, but it would be great if it could be fixed.

Thanks for the hard work.

**Comment by Shinzin** [comment]
The Log Uploader issue is not in Indigo. iI was an issue in script.tvaddons.debug.log. That issue has been fixed as of Dec 4 2018.
