### ISSUE TITLE
Not a zip file

### ISSUE THREAD

**Issue by Parsival1973** [tvaddonsco/plugin.program.indigo#12]
On official release 18 indigo provides error not a zip file when trying to access.

**Comment by eeden003** [comment]
Same problem here on multiple devices since months ! Have send messages to
tvaddons on Facebook months ago, but the said it works perfectly.....😕

Op wo 13 feb. 2019 00:43 schreef Jason Smith <notifications@github.com:

**Comment by eeden003** [comment]
Just to be CLEAR, after installing the newest release kodi 18 still thesame problems(error-codes) with indigo !

**Comment by Parsival1973** [comment]
Yup multiple devices here as well. It seemed to work for the release candidates of Kodi 18 but not the official release... I just had one system upgrade itself to 18 from 17.6 and it went from functional to broken.

I have done clean installs of kodi 18 and only installing indigo and same problem.

**Comment by tvaddonsco** [comment]
We're pushing an update to fix this shortly, thanks for reporting! @eeden003 @Parsival1973

**Comment by eeden003** [comment]
Thanks ! I hope it will fix the problems, we'll let you know !😃

Op za 16 feb. 2019 18:24 schreef TV ADDONS <notifications@github.com:

**Comment by Parsival1973** [comment]
Installed the beta 4.0.11 and it still has the same problem.
