### ISSUE TITLE
Show real-debrid vpn status

### ISSUE THREAD

**Issue by peno64** [tvaddonsco/plugin.program.indigo#13]
This is not a bug, but a feature request.

It would be nice if it could be possible to show the status of https://real-debrid.com/vpn
Especially with some vpns it can happen that real-debrid locks all access from these addresses. I provide two example. One working, one not working (note that the one not working could change in the near future to working because I asked real-debrid to unlock that ip address.
As you can see from the two examples the page can show if the ip address is white-listed or blocked which is interesting information to know if links from real-debrid can be streamed or not.
Note that I added .txt after the actual extension to be able to upload these two files.

So it would be nice if you had a menu item which shows this status.

Thank you

[vpnok.htm.txt](https://github.com/tvaddonsco/plugin.program.indigo/files/2862532/vpnok.htm.txt)
[vpnnok.htm.txt](https://github.com/tvaddonsco/plugin.program.indigo/files/2862533/vpnnok.htm.txt)

**Comment by tvaddonsco** [comment]
Good idea, we'll look into it. Thank you!
