### ISSUE TITLE
Constant Notifications from Indigo (sometimes blank) despite Opt-out

### ISSUE THREAD

**Issue by ix4** [tvaddonsco/plugin.program.indigo#19]
I keep receiving annoying notification "popups" from Indigo every day, sometimes multiple per day. This is despite the fact that I've Opted-out properly. Nearly all of these "community notifications" are just self-serving advertisements for VPN subscriptions.
I've gotten 3 "notifications" today already.
![screenshot](https://i.imgur.com/LLFf0bZ.png)

**Comment by Cizzzzz** [comment]
Why would you close this ticket? It still is not solved with rel 4.0.20 and ‘unsubscribe’ to true. Notifications keep popping up.
