### ISSUE TITLE
Update to URL Resolver add-on failing in Kodi 19 due to Indigo dependency

### ISSUE THREAD

**Issue by Djtrip83** [tvaddonsco/plugin.program.indigo#20]
I am on Kodi 19 and I cannot update the URL Resolver add-on simply because of the Indigo dependency not being compatible with Kodi 19. This affects any update where the add-on has such dependency. Can we please remove the dependency so the add-on can be updated?

**Comment by CHANGERROM** [comment]
If índigo does not  work in kodi 19,Who had the great idea to put it in?

**Comment by Djtrip83** [comment]
Exactly!

[Other add-ons](https://github.com/pressplaykodi/repository.pressplay/issues/4) are doing the same too apparently...

**Comment by ricky151** [comment]
I went back to Kodi 18.something. It’s much more stable and everything still runs good on it.

**Comment by CHANGERROM** [comment]
Ok, I'll check it out.

**Comment by tvaddonsco** [comment]
Dependency has been removed, apologies for the trouble.
